### PR TITLE
image pull policy

### PR DESCRIPTION
**Pull request by dsavchenko**
IfNotPresent + :latest will no pull the new image even if it is changed

### CODE REVIEW

**Comment by volodymyrss** [comment]
yes, that's why it's set as value. that way any chart version corresponds to all component versions set with image tags.
If not, chart version has little relation to the actual platform version.

We wrote it here:

https://github.com/oda-hub/doc-handbook#current-strategy

**Comment by dsavchenko** [comment]
Then we should not use :latest at all. We could fix the tag in the release. 

My point here was that the combination of :latest + IfNotPresent is maximally unpredictable. It depends on the moment when one first pulls the image from dockerhub. In this frame using Always was better.

**Comment by volodymyrss** [comment]
Indeed we should not. 
For development - we use current versions. 
For release - we will freeze tags (as noted in the handbook). `latest` here is a placeholder with little no use. Since we do not have a released tag. And we do not necessarily want to bump oda-chart for every single development update.

I find latest is useful in a  case: when one wants to run the latest version of the application once, without thinking much of the version used. In this sense, for pre-release version, it is sort of appropriate. With caution.

Sorry if it caused confusion.

I  largely share this reasoning about latest tags:

https://vsupalov.com/docker-latest-tag/

**Comment by dsavchenko** [comment]
ok, then I will change it back
anyway, it is not principal and can be overridden in site values
I was just confused for some time, why testing deployment is not updating the container

**Comment by volodymyrss** [comment]
I quite understand! I had the same issue, and it is exactly why I decided consider `latest` generally dangerous, like also described in that link. 
But then, in some rare but persistent situation latest still seems like a natural choice. 
Sorry it caused trouble and extra work!

**Review by volodymyrss — APPROVED** [review]

**Comment by volodymyrss** [comment]
sure, why not merge an empty PR.

**Pull request merged**
