### PR TITLE
Fix for #13

### PR DESCRIPTION
**Pull request by dsavchenko**
Fix for #13

### CODE REVIEW

**Comment by dsavchenko** [comment]
Something wrong here. Timeout in readiness/liveness probe. When I try to manually invoke the command in a running container, it hangs when sourcing init.sh which is very strange
Without probes, all run fine. 
Anyway, I had problems with these probes all the way on my deployments 
@volodymyrss  could you take a look

**Comment by volodymyrss** [comment]
you can just switch off async_dispatcher, it will now completely remove these additional containers together with their probes

**Review by volodymyrss — APPROVED** [review]

**Comment by volodymyrss** [comment]
but yeah, init.sh are needed there

**Comment by volodymyrss** [comment]
I cab merge and then fix myself. But please confirm if you can disable then with values.

**Comment by volodymyrss** [comment]
I specifically added this disabling because there was the same issue you experience and did not bother to fix. It's also much slower to start 4 contaners, and async_dispatcher funtionality is quite detached from the rest.

**Comment by dsavchenko** [comment]
I don't see the disabling, is it merged? The only place where async_dispatcher used is setting env variable.

**Pull request merged**
